### ISSUE TITLE
Unresolved compilation problem when running program

### ISSUE THREAD

**Issue by keefoong09** [ETDA/PDFSigningAndTimestamp#14]
Hi,

When I try to run the program from Eclipse I got the error as below:
```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The constructor SunPKCS11(ByteArrayInputStream) is undefined

	at main.SignAndTimeStamp.signWithTSA(SignAndTimeStamp.java:205)
	at sample.TestSignAndStamp.main(TestSignAndStamp.java:36)
```
Am I missing some library in here? 

Thanks in advance.

**Comment by nathamETDA** [comment]
@keefoong09 
Hi there,
Please check JDK version, the constructor SunPKCS11(ByteArrayInputStream) in not available in JDK 9++.
This code use JDK 8
